# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: chmod +x ./gradlew && ./gradlew build --scan -s

workflows:
  gradle-test:
    jobs:
      - say-hello
